services:
  db:
    image: mysql:5.7
    container_name: mysql
    env_file:
      - ./server/.env
    restart: always
    ports:
      - '33061:3306'
    volumes:
      - db_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    profiles: [localhost]
    networks:
      - video_ai_network

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: backend
    ports:
      - ${HOST_API_PORT}:${CONTAINER_API_HOST}
    environment:
      - NODE_ENV=development
    volumes:
      - ./server:/app
      - ./public:/app/public
      - /app/node_modules
    # depends_on:
    #   - db
    networks:
      - video_ai_network

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    container_name: frontend
    ports:
      - ${HOST_WEB_PORT}:${CONTAINER_WEB_HOST}
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - FAST_REFRESH=false
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
    networks:
      - video_ai_network

volumes:
  db_data:

networks:
  video_ai_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/24
