services:
  db:
    image: mysql:5.7
    container_name: mysql
    env_file:
      - ./server/.env
    restart: always
    ports:
      - '33061:3306'
    volumes:
      - db_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  server:
    build: ./server
    container_name: backend
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - db

  client:
    build: ./client
    container_name: frontend
    ports:
      - '5173:5173'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - FAST_REFRESH=false
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server

volumes:
  db_data:
