export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const FETCH_TRENDS_REQUEST = 'FETCH_TRENDS_REQUEST';
export const FETCH_TRENDS_SUCCESS = 'FETCH_TRENDS_SUCCESS';
export const FETCH_TRENDS_FAILURE = 'FETCH_TRENDS_FAILURE';

export const GENERATE_TEXT_REQUEST = 'GENERATE_TEXT_REQUEST';
export const GENERATE_TEXT_SUCCESS = 'GENERATE_TEXT_SUCCESS';
export const GENERATE_TEXT_FAILURE = 'GENERATE_TEXT_FAILURE';

export const FETCH_TEXTSCRIPTS_REQUEST = 'FETCH_TEXTSCRIPTS_REQUEST';
export const FETCH_TEXTSCRIPTS_SUCCESS = 'FETCH_TEXTSCRIPTS_SUCCESS';
export const FETCH_TEXTSCRIPTS_FAILURE = 'FETCH_TEXTSCRIPTS_FAILURE';
