export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const FETCH_TRENDS_REQUEST = 'FETCH_TRENDS_REQUEST';
export const FETCH_TRENDS_SUCCESS = 'FETCH_TRENDS_SUCCESS';
export const FETCH_TRENDS_FAILURE = 'FETCH_TRENDS_FAILURE';

export const GENERATE_TEXT_REQUEST = 'GENERATE_TEXT_REQUEST';
export const GENERATE_TEXT_SUCCESS = 'GENERATE_TEXT_SUCCESS';
export const GENERATE_TEXT_FAILURE = 'GENERATE_TEXT_FAILURE';
export const RESET_GENERATE_SCRIPT = 'RESET_GENERATE_SCRIPT';

export const FETCH_TEXTSCRIPTS_REQUEST = 'FETCH_TEXTSCRIPTS_REQUEST';
export const FETCH_TEXTSCRIPTS_SUCCESS = 'FETCH_TEXTSCRIPTS_SUCCESS';
export const FETCH_TEXTSCRIPTS_FAILURE = 'FETCH_TEXTSCRIPTS_FAILURE';

export const CREATE_TEXTSCRIPT_REQUEST = 'CREATE_TEXTSCRIPT_REQUEST';
export const CREATE_TEXTSCRIPT_SUCCESS = 'CREATE_TEXTSCRIPT_SUCCESS';
export const CREATE_TEXTSCRIPT_FAILURE = 'CREATE_TEXTSCRIPT_FAILURE';

export const UPDATE_TEXTSCRIPT_REQUEST = 'UPDATE_TEXTSCRIPT_REQUEST';
export const UPDATE_TEXTSCRIPT_SUCCESS = 'UPDATE_TEXTSCRIPT_SUCCESS';
export const UPDATE_TEXTSCRIPT_FAILURE = 'UPDATE_TEXTSCRIPT_FAILURE';

export const FETCH_VIDEOS_REQUEST = 'FETCH_VIDEOS_REQUEST';
export const FETCH_VIDEOS_SUCCESS = 'FETCH_VIDEOS_SUCCESS';
export const FETCH_VIDEOS_FAILURE = 'FETCH_VIDEOS_FAILURE';

export const FETCH_AVATARS_REQUEST = 'FETCH_AVATARS_REQUEST';
export const FETCH_AVATARS_SUCCESS = 'FETCH_AVATARS_SUCCESS';
export const FETCH_AVATARS_FAILURE = 'FETCH_AVATARS_FAILURE';

export const GENERATE_VIDEO_REQUEST = 'GENERATE_VIDEO_REQUEST';
export const GENERATE_VIDEO_SUCCESS = 'GENERATE_VIDEO_SUCCESS';
export const GENERATE_VIDEO_FAILURE = 'GENERATE_VIDEO_FAILURE';

export const LINK_PLATFORM_REQUEST = 'LINK_PLATFORM_REQUEST';
export const LINK_PLATFORM_SUCCESS = 'LINK_PLATFORM_SUCCESS';
export const LINK_PLATFORM_FAILURE = 'LINK_PLATFORM_FAILURE';

export const REVOKE_PLATFORM_REQUEST = 'REVOKE_PLATFORM_REQUEST';
export const REVOKE_PLATFORM_SUCCESS = 'REVOKE_PLATFORM_SUCCESS';
export const REVOKE_PLATFORM_FAILURE = 'REVOKE_PLATFORM_FAILURE';

export const GET_LINKED_ACCOUNTS_REQUEST = 'GET_LINKED_ACCOUNTS_REQUEST';
export const GET_LINKED_ACCOUNTS_SUCCESS = 'GET_LINKED_ACCOUNTS_SUCCESS';
export const GET_LINKED_ACCOUNTS_FAILURE = 'GET_LINKED_ACCOUNTS_FAILURE';

export const FETCH_LINKED_ACCOUNTS_REQUEST = 'FETCH_LINKED_ACCOUNTS_REQUEST';
export const FETCH_LINKED_ACCOUNTS_SUCCESS = 'FETCH_LINKED_ACCOUNTS_SUCCESS';
export const FETCH_LINKED_ACCOUNTS_FAILURE = 'FETCH_LINKED_ACCOUNTS_FAILURE';

export const UPLOAD_VIDEO_REQUEST = 'UPLOAD_VIDEO_REQUEST';
export const UPLOAD_VIDEO_SUCCESS = 'UPLOAD_VIDEO_SUCCESS';
export const UPLOAD_VIDEO_FAILURE = 'UPLOAD_VIDEO_FAILURE';

export const FETCH_API_KEY_REQUEST = 'FETCH_API_KEY_REQUEST';
export const FETCH_API_KEY_SUCCESS = 'FETCH_API_KEY_SUCCESS';
export const FETCH_API_KEY_FAILURE = 'FETCH_API_KEY_FAILURE';

export const UPDATE_API_KEY_REQUEST = 'UPDATE_API_KEY_REQUEST';
export const UPDATE_API_KEY_SUCCESS = 'UPDATE_API_KEY_SUCCESS';
export const UPDATE_API_KEY_FAILURE = 'UPDATE_API_KEY_FAILURE';

export const GET_TREND_REQUEST = 'GET_TREND_REQUEST';
export const GET_TREND_SUCCESS = 'GET_TREND_SUCCESS';
export const GET_TREND_FAILURE = 'GET_TREND_FAILURE';

export const FETCH_SUBTITLE_REQUEST = 'FETCH_SUBTITLE_REQUEST';
export const FETCH_SUBTITLE_SUCCESS = 'FETCH_SUBTITLE_SUCCESS';
export const FETCH_SUBTITLE_FAILURE = 'FETCH_SUBTITLE_FAILURE';

export const SAVE_SUBTITLE_REQUEST = 'SAVE_SUBTITLE_REQUEST';
export const SAVE_SUBTITLE_SUCCESS = 'SAVE_SUBTITLE_SUCCESS';
export const SAVE_SUBTITLE_FAILURE = 'SAVE_SUBTITLE_FAILURE';

export const MERGE_VIDEO_REQUEST = 'MERGE_VIDEO_REQUEST';
export const MERGE_VIDEO_SUCCESS = 'MERGE_VIDEO_SUCCESS';
export const MERGE_VIDEO_FAILURE = 'MERGE_VIDEO_FAILURE';
